#!/usr/bin/env bash
#
# collect_diff_context.sh
#
# Collects git context for the mobile-tc-harness skill.
# Outputs a structured Markdown summary that the skill consumes during Stage 1.
#
# Usage:
#   ./collect_diff_context.sh <commit-range>
#
# Examples:
#   ./collect_diff_context.sh HEAD~1..HEAD
#   ./collect_diff_context.sh v2.3.0..HEAD
#   ./collect_diff_context.sh release/v2.3.x..release/v2.4.0
#
# Output: structured Markdown to stdout. No side effects.

set -euo pipefail

# ----- Arg parsing -----

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <commit-range>" >&2
  echo "Example: $0 HEAD~1..HEAD" >&2
  exit 1
fi

RANGE="$1"

# ----- Sanity checks -----

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "Error: not inside a git repository" >&2
  exit 2
fi

# Verify the range is resolvable
if ! git rev-list --quiet "$RANGE" 2>/dev/null; then
  # Some ranges (like HEAD~1..HEAD on a single-commit repo) need a different probe
  if ! git log --oneline -1 "$RANGE" >/dev/null 2>&1; then
    echo "Error: commit range '$RANGE' could not be resolved" >&2
    echo "Hint: run 'git log --oneline -20' to see available commits" >&2
    exit 3
  fi
fi

# ----- Output -----

cat <<EOF
# Diff context summary

Generated by: \`collect_diff_context.sh $RANGE\`
Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Working tree: $(git rev-parse --show-toplevel)
HEAD: $(git rev-parse HEAD)
Range: $RANGE

---

## Commit log (oneline)

\`\`\`
$(git log --oneline "$RANGE" 2>/dev/null || echo "(no commits in range)")
\`\`\`

---

## Diff stat

\`\`\`
$(git diff --stat "$RANGE" 2>/dev/null || echo "(no diff for range)")
\`\`\`

---

## Changed files (full list)

\`\`\`
$(git diff --name-status "$RANGE" 2>/dev/null || echo "(no files)")
\`\`\`

---

## Commit messages (full, not truncated)

EOF

# Each commit's full message, separated for downstream parsing
git log --format="### %h — %s%n%n%b%n%n---%n" "$RANGE" 2>/dev/null || echo "(no commits)"

cat <<EOF

---

## File-level signals (heuristic)

> The skill's Stage 2 (Triage) consumes the file list above. These signals are hints, not classifications.

EOF

# Heuristic signal detection — extend in references/tc-taxonomy.md
FILES=$(git diff --name-only "$RANGE" 2>/dev/null || echo "")

if [[ -n "$FILES" ]]; then
  if echo "$FILES" | grep -qiE '(manifest|AndroidManifest)\.xml$'; then
    echo "- 🚨 \`manifest-change\` detected — permission / capability review needed"
  fi
  if echo "$FILES" | grep -qiE 'plist$'; then
    echo "- 🚨 \`iOS-plist-change\` detected — Info.plist or entitlements modified"
  fi
  if echo "$FILES" | grep -qiE '(Lifecycle|OnApplicationPause|AppDelegate)'; then
    echo "- 🚨 \`lifecycle-change\` detected — high blast radius, regression sweep needed"
  fi
  if echo "$FILES" | grep -qiE 'Migrator|Migration'; then
    echo "- 🚨 \`data-migration\` detected — old-save compatibility critical"
  fi
  if echo "$FILES" | grep -qiE 'Loader|Async|UniTask'; then
    echo "- ⚠️  \`async-or-loader-change\` detected — race condition risk"
  fi
  if echo "$FILES" | grep -qiE 'Notification|Permission'; then
    echo "- ⚠️  \`permission-flow\` detected"
  fi
  if echo "$FILES" | grep -qiE '(persistentDataPath|StreamingAssets)'; then
    echo "- ⚠️  \`cross-platform-path\` reference detected — iOS Prepared flag candidate"
  fi
  if echo "$FILES" | grep -qiE '\.(prefab|unity|asset)$'; then
    echo "- ℹ️  Unity asset changes — visual / scene regression possible"
  fi
  if echo "$FILES" | grep -qiE 'Test.*\.cs$|.*Test\.cs$'; then
    echo "- ℹ️  Test code present in diff — verify coverage of new code paths"
  else
    echo "- ⚠️  No test files present in diff — automation gap to flag in TC output"
  fi
else
  echo "- (no files changed)"
fi

cat <<EOF

---

## Next step

This summary is consumed by SKILL.md Stage 1 (Collect). The skill will:

1. Read this output
2. Optionally read Notion patch + dev notes (if \`notion-read\` arg given)
3. Proceed to Stage 2 (Triage) using \`references/tc-taxonomy.md\`

End of context summary.
EOF
